### ISSUE TITLE
Ip2ip errors on code strings

### ISSUE THREAD

**Issue by YYJohnston** [bitfocus/companion-module-globalcache-itac-ir#6]
This is the code I got from Global Cache for Samsung TV power off: 
sendir,1:1,1,38000,1,1,173,173,21,65,21,65,21,65,21,21,21,21,21,21,21,21,21,21,21,65,21,65,21,65,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,65,21,65,21,21,21,21,21,65,21,65,21,65,21,65,21,21,21,21,21,65,21,65,21,21,21,1832

If I leave the entire string in there, it appears to take it but will not fire a command. I understand that I need the part starting with the 38000 and select the port from the drop down instead of in the 1:1 part of the code, however, if I remove the sendir part it turns red and wont save, and, also does not run the code. According to some people on Facebook this is known issue and there was a fix, however, I cannot find that fix. I am on a PC. 

I saw in pull requests that this was fixed, however, I am new to the platform, the only software I know is what is on companions website, I don't know how to take the fix and apply it. Please be kind if I am overlooking something simple.

**Comment by lfrisk** [comment]
[Here is a link](https://github.com/bitfocus/companion-module-globalcache-itac-ir/issues/4#issuecomment-789102170) to another thread that might help you

**Comment by sydneyjd** [comment]
@YYJohnston Did you manage to get this working? It should be fixed in the latest stable build. If so, can this issue be closed?

**Comment by YYJohnston** [comment]
We rolled back to an old build, we will upgrade and test. You can close the
thread. Thanks.
