### ISSUE TITLE
v2.0.1 is still broken - Actions don't do anything

### ISSUE THREAD

**Issue by tpk001** [bitfocus/companion-module-globalcache-itac-ir#8]
Companion: 3.1.0+6155-beta-4c917243
Module Ver: 2.0.1

History:
3.1.0 beta 78b62679 - Working
3.1.0 beta abace5a - Connector v2.0.0 - Connector Error. Module does not start with v2.0.0
3.1.0 beta 4c917243 - Connector 2.0.1 - Connector is fine. Button actions don't do anything. No error logs.

Thanks

**Comment by tpk001** [comment]
Actions don't work with 2.0.2 as well.

**Comment by josephdadams** [comment]
pushed version v2.0.3. Please try it and let me know if you still need support.

**Comment by tpk001** [comment]
Beta branch is not updated yet.
https://github.com/bitfocus/companion/commits/beta

**Comment by josephdadams** [comment]
It can take up to 6 hours before you see a new build.
